openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:7000
  description: Generated server url
paths:
  /api/sauces/{id}:
    get:
      tags:
      - sauce-controller
      operationId: find
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Sauce'
    put:
      tags:
      - sauce-controller
      operationId: update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sauce'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Sauce'
    delete:
      tags:
      - sauce-controller
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Sauce'
  /api/sauces:
    get:
      tags:
      - sauce-controller
      operationId: findAll
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sauce'
    post:
      tags:
      - sauce-controller
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sauce'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Sauce'
components:
  schemas:
    Sauce:
      required:
      - description
      - heatLevel
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          pattern: "^[a-zA-Z ]+$"
          type: string
        description:
          pattern: "^[a-zA-Z ]+$"
          type: string
        heatLevel:
          type: integer
          format: int32
